from enum import Enum

class EventType(str, Enum):
    # SYSTEM
    SYSTEM_BOOT = "SYSTEM_BOOT"
    SYSTEM_READY = "SYSTEM_READY"
    SYSTEM_ERROR = "SYSTEM_ERROR"
    SYSTEM_RESET = "SYSTEM_RESET"

    # STATE
    STATE_UPDATED = "STATE_UPDATED"
    BOARD_UPDATED = "BOARD_UPDATED"
    MOVE_APPLIED = "MOVE_APPLIED"
    STATE_SYNCHRONIZED = "STATE_SYNCHRONIZED"

    # VISION
    VISION_FRAME_CAPTURED = "VISION_FRAME_CAPTURED"
    VISION_FRAME_PROCESSED = "VISION.FRAME_PROCESSED"
    VISION_BOARD_DETECTED = "VISION_BOARD_DETECTED"
    VISION_MOVE_DETECTED = "VISION_MOVE_DETECTED"

    # ENGINE
    ENGINE_ANALYSIS_REQUESTED = "ENGINE_ANALYSIS_REQUESTED"
    ENGINE_ANALYSIS_STARTED = "ENGINE_ANALYSIS_STARTED"
    ENGINE_MOVE_GENERATED = "ENGINE_MOVE_GENERATED"
    ENGINE_ANALYSIS_COMPLETED = "ENGINE_ANALYSIS_COMPLETED"

    # ROBOT
    ROBOT_MOVE_REQUESTED = "ROBOT_MOVE_REQUESTED"
    ROBOT_MOVE_STARTED = "ROBOT_MOVE_STARTED"
    ROBOT_MOVE_COMPLETED = "ROBOT_MOVE_COMPLETED"
    ROBOT_STATUS_UPDATED = "ROBOT.STATUS_UPDATED"

    # RECOVERY
    RECOVERY_STARTED = "RECOVERY_STARTED"
    RECOVERY_COMPLETED = "RECOVERY_COMPLETED"
    EMERGENCY_STOP = "EMERGENCY_STOP"

    # DIAGNOSTICS
    DIAGNOSTICS_UPDATED = "DIAGNOSTICS_UPDATED"
    HEARTBEAT = "HEARTBEAT"

    # UI / NOTIFICATION
    UI_ACTION = "UI_ACTION"
    UI_TOAST = "UI_TOAST"
    UI_VIEW_CHANGED = "UI_VIEW_CHANGED"

    # SOCKET
    SOCKET_EMIT = "SOCKET_EMIT"

    # GAMEPLAY (High-level)
    GAME_START = "GAME_START"
    GAME_PAUSE = "GAME_PAUSE"
    GAME_RESET = "GAME_RESET"
    GAME_UNDO = "GAME_UNDO"
    GAME_PLAYER_MOVE = "GAME_PLAYER_MOVE"


class GameEvents(str, Enum):
    MOVE_APPLIED = EventType.MOVE_APPLIED.value
    PLAYER_MOVE = EventType.GAME_PLAYER_MOVE.value
    START = EventType.GAME_START.value
    PAUSE = EventType.GAME_PAUSE.value
    RESET = EventType.GAME_RESET.value
    UNDO = EventType.GAME_UNDO.value


class EngineEvents(str, Enum):
    ANALYSIS_REQUESTED = EventType.ENGINE_ANALYSIS_REQUESTED.value
    ANALYSIS_STARTED = EventType.ENGINE_ANALYSIS_STARTED.value
    ANALYSIS_COMPLETED = EventType.ENGINE_ANALYSIS_COMPLETED.value
    MOVE_GENERATED = EventType.ENGINE_MOVE_GENERATED.value


class VisionEvents(str, Enum):
    FRAME_CAPTURED = EventType.VISION_FRAME_CAPTURED.value
    FRAME_PROCESSED = EventType.VISION_FRAME_PROCESSED.value
    MOVE_DETECTED = EventType.VISION_MOVE_DETECTED.value


class SystemEvents(str, Enum):
    STATE_SYNCHRONIZED = EventType.STATE_UPDATED.value
    SYSTEM_RESET = EventType.SYSTEM_RESET.value
    SYSTEM_ERROR = EventType.SYSTEM_ERROR.value
    DIAGNOSTICS_UPDATED = EventType.DIAGNOSTICS_UPDATED.value
