from enum import Enum, unique

@unique
class SystemErrorCode(str, Enum):
    # Bootstrap & Runtime
    BOOTSTRAP_FAILED = "BOOTSTRAP_FAILED"
    RUNTIME_LOOP_ERROR = "RUNTIME_LOOP_ERROR"

    # Auth & Security
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    INVALID_TOKEN = "INVALID_TOKEN"
    RATE_LIMITED = "RATE_LIMITED"

    # Hardware
    ROBOT_CONNECTION_FAILED = "ROBOT_CONNECTION_FAILED"
    ROBOT_MOTION_ERROR = "ROBOT_MOTION_ERROR"
    VISION_CAMERA_ERROR = "VISION_CAMERA_ERROR"
    VISION_DETECTION_FAILED = "VISION_DETECTION_FAILED"
    ENGINE_PROCESS_CRASHED = "ENGINE_PROCESS_CRASHED"

    # Application Logic
    INVALID_MOVE = "INVALID_MOVE"
    STATE_TRANSITION_ERROR = "STATE_TRANSITION_ERROR"
    PERSISTENCE_FAILURE = "PERSISTENCE_FAILURE"

    # UI / Socket
    INVALID_PAYLOAD = "INVALID_PAYLOAD"
    PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE"
